targets:
  $default:
    builders:
      showkase_gen:
        enabled: true
        generate_for:
          exclude:
            - test
#            - example
#          include:
#            - test/integration/*

builders:
  showkase_gen:
    import: "package:showkase_gen/builder.dart"
    build_extensions: { ".dart": [".showkase.dart"] }
    builder_factories: ["showkase"]
    auto_apply: dependents
    build_to: source